on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: ["**"]

name: Test on Ubuntu
jobs:
  test-ubuntu-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "sudo apt-get update && sudo apt-get install git build-essential cmake"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Dchannel_tests=ON && cmake --build . --config Release"

      - name: Run Tests
        run: "./build/tests/channel-tests"

  test-ubuntu-debug:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "sudo apt-get update && sudo apt-get install git build-essential cmake"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Dchannel_tests=ON && cmake --build . --config Debug"

      - name: Run Tests
        run: "./build/tests/channel-tests"
