on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
  pull_request:
    branches: ["**"]

name: Test on Fedora-Linux
jobs:
  test-fedora-34-release:
    runs-on: ubuntu-latest
    container: fedora:34
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "dnf install -y make automake git gcc gcc-c++ kernel-devel cmake"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Dchannel_tests=ON && cmake --build . --config Release"

  test-fedora-34-debug:
    runs-on: ubuntu-latest
    container: fedora:34
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "dnf install -y make git automake gcc gcc-c++ kernel-devel cmake"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Dchannel_tests=ON && cmake --build . --config Debug"

  test-fedora-35-release:
    runs-on: ubuntu-latest
    container: fedora:35
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "dnf install -y make git automake gcc gcc-c++ kernel-devel cmake"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Dchannel_tests=ON && cmake --build . --config Release"

  test-fedora-35-debug:
    runs-on: ubuntu-latest
    container: fedora:35
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "dnf install -y make automake git gcc gcc-c++ kernel-devel cmake"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Dchannel_tests=ON && cmake --build . --config Debug"

  test-fedora-36-release:
    runs-on: ubuntu-latest
    container: fedora:36
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "dnf install -y make automake git gcc gcc-c++ kernel-devel cmake"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Dchannel_tests=ON && cmake --build . --config Release"

  test-fedora-36-debug:
    runs-on: ubuntu-latest
    container: fedora:36
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "dnf install -y make automake git gcc gcc-c++ kernel-devel cmake"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Dchannel_tests=ON && cmake --build . --config Debug"
