on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
  pull_request:
    branches: ["**"]

name: Test on Fedora-Linux
jobs:
  test-fedora-38-release:
    runs-on: ubuntu-latest
    container: fedora:38
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "dnf install -y make automake git gcc gcc-c++ kernel-devel cmake"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Dchannel_tests=ON && cmake --build . --config Release"

      - name: Run Tests
        run: "./build/channel_tests"

  test-fedora-38-debug:
    runs-on: ubuntu-latest
    container: fedora:38
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "dnf install -y make automake git gcc gcc-c++ kernel-devel cmake"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Dchannel_tests=ON && cmake --build . --config Debug"

      - name: Run Tests
        run: "./build/channel_tests"
